//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_sitioweb.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaHorarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listaHorarios(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaHorarios", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> listaHorariosAsync(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarReserva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertarReserva(int p, int m, string h, string r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarReserva", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertarReservaAsync(int p, int m, string h, string r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNombrePaciente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetNombrePaciente(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNombrePaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetNombrePacienteAsync(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarPaciente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertarPaciente(int id, string n, string ap, string fecha, string sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertarPacienteAsync(int id, string n, string ap, string fecha, string sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertarUsuario(int id, string pasword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertarUsuarioAsync(int id, string pasword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Autentificar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Autentificar(int user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Autentificar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AutentificarAsync(int user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaPacientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listaPacientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaPacientes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> listaPacientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatoMedico", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DatoMedico(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatoMedico", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DatoMedicoAsync(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaReservas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListaReservas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaReservas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListaReservasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication_sitioweb.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication_sitioweb.ServiceReference1.WebService1Soap>, WebApplication_sitioweb.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet listaHorarios(int i) {
            return base.Channel.listaHorarios(i);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> listaHorariosAsync(int i) {
            return base.Channel.listaHorariosAsync(i);
        }
        
        public int InsertarReserva(int p, int m, string h, string r) {
            return base.Channel.InsertarReserva(p, m, h, r);
        }
        
        public System.Threading.Tasks.Task<int> InsertarReservaAsync(int p, int m, string h, string r) {
            return base.Channel.InsertarReservaAsync(p, m, h, r);
        }
        
        public string GetNombrePaciente(int i) {
            return base.Channel.GetNombrePaciente(i);
        }
        
        public System.Threading.Tasks.Task<string> GetNombrePacienteAsync(int i) {
            return base.Channel.GetNombrePacienteAsync(i);
        }
        
        public int InsertarPaciente(int id, string n, string ap, string fecha, string sexo) {
            return base.Channel.InsertarPaciente(id, n, ap, fecha, sexo);
        }
        
        public System.Threading.Tasks.Task<int> InsertarPacienteAsync(int id, string n, string ap, string fecha, string sexo) {
            return base.Channel.InsertarPacienteAsync(id, n, ap, fecha, sexo);
        }
        
        public int InsertarUsuario(int id, string pasword) {
            return base.Channel.InsertarUsuario(id, pasword);
        }
        
        public System.Threading.Tasks.Task<int> InsertarUsuarioAsync(int id, string pasword) {
            return base.Channel.InsertarUsuarioAsync(id, pasword);
        }
        
        public int Autentificar(int user, string password) {
            return base.Channel.Autentificar(user, password);
        }
        
        public System.Threading.Tasks.Task<int> AutentificarAsync(int user, string password) {
            return base.Channel.AutentificarAsync(user, password);
        }
        
        public System.Data.DataSet listaPacientes() {
            return base.Channel.listaPacientes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> listaPacientesAsync() {
            return base.Channel.listaPacientesAsync();
        }
        
        public System.Data.DataSet DatoMedico(int i) {
            return base.Channel.DatoMedico(i);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DatoMedicoAsync(int i) {
            return base.Channel.DatoMedicoAsync(i);
        }
        
        public System.Data.DataSet ListaReservas() {
            return base.Channel.ListaReservas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListaReservasAsync() {
            return base.Channel.ListaReservasAsync();
        }
    }
}
